
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ben
 */
public class BuseyPanel extends javax.swing.JFrame {

    /**
     * Creates new form BuseyPanel
     */
    private volatile String imgPath;
    File f = null;
    File image = null;
    volatile String quote;
    ArrayList<String> quotesList = new ArrayList<String>();
    public static BuseyPanel bp;

    public BuseyPanel() {

        
        try{
            //loads the image
            getRandomGary();

            getRandomQuote();

            //System.out.println("Current Directory:" + new File(".").getCanonicalPath());

            
        }catch(Exception e){
            System.out.println("Error loading image file" + e);
        }
        initComponents();
        
    }

    /**
     * Gets a random file from the "Images" directory and sets its path to the imgPath variable.
     * The imgPath variable is called by the imageLabel.setIcon() method to show the random Gary.
     */
    private void getRandomGary(){
        f = new File("Images");
        File[] paths = f.listFiles();
        Random rand = new Random();
        int randInt = rand.nextInt(paths.length);
        image = paths[randInt];
        imgPath = image.getAbsolutePath();
        System.out.println("imgPath: " + imgPath);
    }

    /**
     * reads the quotes text file.  Each line is added as an element to the quotesList ArrayList.
     */
    private void getRandomQuote(){
        try{

            BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream("quotes.txt")));
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();


                if (!line.equals("")){
                    quotesList.add(line);
                }
                else{
                    continue;
                }
            }

            br.close();

            Random quoteRand = new Random();
            int randInt = quoteRand.nextInt(quotesList.size());

            quote = quotesList.get(randInt).toString();
            System.out.print("");


        }catch(Exception e){
            System.out.println("Error reading quotes file:" + e);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1240, 2147483647));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(1210, 9999));
        jPanel2.setPreferredSize(new java.awt.Dimension(1240, 920));
        jPanel2.setLayout(null);

        imageLabel.setBackground(new java.awt.Color(0, 0, 0));
        imageLabel.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        imageLabel.setForeground(new java.awt.Color(255, 51, 0));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(imgPath));
        imageLabel.setText("<html> <center> <div style=\"padding-botton: 12px;\">" + quote  + "</div></center></html>");
        imageLabel.setToolTipText("");
        imageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imageLabel.setAlignmentX(40.0F);
        imageLabel.setAlignmentY(0.0F);
        imageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imageLabel.setIconTextGap(40);
        imageLabel.setMaximumSize(new java.awt.Dimension(1240, 920));
        imageLabel.setMinimumSize(new java.awt.Dimension(800, 600));
        imageLabel.setOpaque(true);
        imageLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        imageLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imageLabelComponentResized(evt);
            }
        });
        jPanel2.add(imageLabel);
        imageLabel.setBounds(40, 0, 1170, 820);

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resetButton.setText("I need more, Gary!");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resetButton);
        resetButton.setBounds(0, 820, 1210, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1210, 880);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * reloads the page with a new image and quote.
     * @param evt 
     */
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        BuseyThoughts.refreshPage(this);

        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void imageLabelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imageLabelComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_imageLabelComponentResized

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        AboutWindow aw = new AboutWindow();
        aw.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuseyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuseyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuseyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuseyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                bp = new BuseyPanel();
                bp.setVisible(true);
                bp.setSize(1240, 940);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu helpMenu;
    public volatile javax.swing.JLabel imageLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
